/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/delivery` | `/delivery`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/addresses`; params?: Router.UnknownInputParams; } | { pathname: `/profile/becomeDelivery`; params?: Router.UnknownInputParams; } | { pathname: `/profile/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/profile/payments`; params?: Router.UnknownInputParams; } | { pathname: `/profile/personalInfo`; params?: Router.UnknownInputParams; } | { pathname: `/profile/preferences`; params?: Router.UnknownInputParams; } | { pathname: `/profile/security`; params?: Router.UnknownInputParams; } | { pathname: `/profile/delivery/earnings`; params?: Router.UnknownInputParams; } | { pathname: `/profile/delivery/vehicleStatus`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/delivery` | `/delivery`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/addresses`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/becomeDelivery`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/payments`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/personalInfo`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/preferences`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/security`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/delivery/earnings`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/delivery/vehicleStatus`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/delivery${`?${string}` | `#${string}` | ''}` | `/delivery${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/orders${`?${string}` | `#${string}` | ''}` | `/orders${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/profile/addresses${`?${string}` | `#${string}` | ''}` | `/profile/becomeDelivery${`?${string}` | `#${string}` | ''}` | `/profile/notifications${`?${string}` | `#${string}` | ''}` | `/profile/payments${`?${string}` | `#${string}` | ''}` | `/profile/personalInfo${`?${string}` | `#${string}` | ''}` | `/profile/preferences${`?${string}` | `#${string}` | ''}` | `/profile/security${`?${string}` | `#${string}` | ''}` | `/profile/delivery/earnings${`?${string}` | `#${string}` | ''}` | `/profile/delivery/vehicleStatus${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/delivery` | `/delivery`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/addresses`; params?: Router.UnknownInputParams; } | { pathname: `/profile/becomeDelivery`; params?: Router.UnknownInputParams; } | { pathname: `/profile/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/profile/payments`; params?: Router.UnknownInputParams; } | { pathname: `/profile/personalInfo`; params?: Router.UnknownInputParams; } | { pathname: `/profile/preferences`; params?: Router.UnknownInputParams; } | { pathname: `/profile/security`; params?: Router.UnknownInputParams; } | { pathname: `/profile/delivery/earnings`; params?: Router.UnknownInputParams; } | { pathname: `/profile/delivery/vehicleStatus`; params?: Router.UnknownInputParams; };
    }
  }
}
